"""
Generate training history for Case Study 3: Modular Arithmetic

DEPRECATED: This script is replaced by modal_train_reference_jax.py which
trains a real neural network on Modal with GPU.

To generate new training data, run:
    modal run case3/scripts/modal_train_reference_jax.py

The training demonstrates the memorization phase of neural networks on
modular arithmetic - the network achieves 100% training accuracy but
does not generalize to the test set without weight decay regularization.

The pre-generated reference_training_loss.csv contains real training
data from a JAX neural network with:
- Architecture: 194 -> 128 -> 128 -> 97 (two hidden layers)
- Activation: ReLU
- Optimizer: Adam (lr=0.001, no weight decay)
- Training: 50000 epochs on ~4705 training examples

See modal_train_reference_jax.py for the actual training implementation.
"""

print("This script is deprecated.")
print("Training data is now generated by modal_train_reference_jax.py")
print("Run: modal run case3/scripts/modal_train_reference_jax.py")
